version: '3'

services:
  django_dhadkan:
    build: .
    container_name: django_dhadkan
    volumes:
      - ../myapp:/myapp/
    command: bash -c "python myapp/manage.py makemigrations && python myapp/manage.py migrate && python myapp/manage.py runserver 0.0.0.0:9000"
    ports:
      - "9000:9000"
    depends_on:
      - nginx_d

  nginx_d:
    build: ../../nginx/
    restart: always
    volumes:
      - ../../nginx/data:/usr/share/nginx/html/
    ports:
      - "80:80"
    environment:
     - NGINX_HOST=mycompany.com
     - NGINX_PORT=80
    # command: /bin/bash -c "envsubst /etc/nginx/site-available/default && exec nginx -g 'daemon off;'"
    container_name: docker_nginx
