version: '3'

services:
  od:
    build: .
    container_name: object_detection
    volumes:
      - ./server:/~/server
      - ./data:/~/models/research/object_detection/mydata
      - ./training:/~/models/research/object_detection/training
      - ./lead_location_detect.ipynb:/~/models/research/object_detection/object_detection.ipynb
      - ./object_detection.py:/~/models/research/lead_detection.py
      - ./execute.py:/~/models/research/execute.py
    ports:
      - '8889:8889'
      - '5000:5000'
    command: bash -c "chmod +x /~/server/app.py && python /~/server/app.py"
