version: '2'

services:
  nginx_d:
    build: .
    restart: always
    volumes:
      - ./data:/usr/share/nginx/html/
    ports:
      - "50:50"
    environment:
     - NGINX_HOST=dkuamr12132.com
     - NGINX_PORT=50
    command: /bin/bash -c "envsubst /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    container_name: docker_nginx
