version: '3'

services:
  django_dhadkan:
    build: .
    container_name: django_dhadkan
    volumes:
      - ../../dhadkan_v3_backend:/dhadkan_v3_backend-0.0.2/
    command: bash -c "python dhadkan_v3_backend-0.0.2/manage.py makemigrations && python dhadkan_v3_backend-0.0.2/manage.py migrate && python dhadkan_v3_backend-0.0.2/manage.py runserver 0.0.0.0:9000"
    ports:
      - "9000:9000"
    depends_on:
      - nginx_d
      - ob

  nginx_d:
    build: ../nginx/
    restart: always
    volumes:
      - ../nginx/data:/usr/share/nginx/html/
    ports:
      - "50:50"
    environment:
     - NGINX_HOST=dkumar123.iitr.ac.in
     - NGINX_PORT=50
    # command: /bin/bash -c "envsubst /etc/nginx/site-available/default && exec nginx -g 'daemon off;'"
    container_name: docker_nginx

  ob:
    build: ../Object_detection
    container_name: object_detection
    volumes:
      - ../Object_detection/server:/~/server
      - ../Object_detection/data:/~/models/research/object_detection/mydata
      - ../Object_detection/training:/~/models/research/object_detection/training
      - ../Object_detection/lead_location_detect.ipynb:/~/models/research/object_detection/object_detection.ipynb
      - ../Object_detection/object_detection.py:/~/models/research/lead_detection.py
      - ../Object_detection/execute.py:/~/models/research/execute.py
    ports:
      - '8889:8889'
      - '5000:5000'
    command: bash -c "chmod +x /~/server/app.py && python /~/server/app.py"
    depends_on:
      - nginx_d
